"""Auto-seed sample portfolios if the table is empty.

Called once on startup from main.py. Safe to call multiple times — it
checks for existing rows and skips if any are found.
"""
import json
from sqlalchemy.orm import Session
from . import models

U = "https://images.unsplash.com/photo-"


def _img(pid, w=600):
    return f"{U}{pid}?auto=format&fit=crop&w={w}&q=80"


def _stat(*p): return [{"value": v, "label": l} for v, l in p]
def _svc(*x): return [{"icon": i, "title": t, "desc": d} for i, t, d in x]
def _skl(*x): return [{"name": n, "percent": p} for n, p in x]
def _proj(*x): return [{"title": t, "category": c, "image": im, "desc": d, "url": "#"} for t, c, im, d in x]
def _tl(*x): return [{"role": r, "company": c, "period": p, "desc": d} for r, c, p, d in x]
def _ach(*x): return [{"icon": i, "title": t, "subtitle": s} for i, t, s in x]
def _tst(*x): return [{"text": t, "author": a, "role": r, "avatar": av} for t, a, r, av in x]

DEF_SOC = {"facebook": "#", "instagram": "#", "linkedin": "#", "twitter": "#", "youtube": "#"}
WHY = _skl(("Client Satisfaction", 98), ("On-Time Delivery", 96), ("Quality Assurance", 99), ("Repeat Clients", 92))


def _biz(slug, theme, layout, name, industry, image, greeting, cta, tagline, about,
         stats, services, why, work, milestones, certs, awards, reviews,
         email, phone, location, hours, established, **o):
    return {"slug": slug, "data": {
        "theme": theme, "layout": layout,
        "name": name, "role": industry, "greeting": greeting, "tagline": tagline,
        "image": image, "ctaText": cta,
        "resumeText": o.get("resumeText", "Our Brochure"), "resumeUrl": "#",
        "socials": DEF_SOC,
        "stats": stats,
        "aboutHeading": o.get("aboutHeading", f"Welcome to {name}"), "about": about,
        "personal": {"email": email, "phone": phone, "location": location,
                     "availability": hours, "languages": established},
        "services": services, "skills": why, "projects": work,
        "experience": milestones, "education": certs,
        "achievements": awards, "testimonials": reviews,
        "hServices": o.get("hServices", "Our Services"),
        "hSkills": o.get("hSkills", "Why Choose Us"),
        "hWork": o.get("hWork", "Our Work"),
        "hResume": o.get("hResume", "Our Journey"),
        "hExperience": o.get("hExperience", "Milestones"),
        "hEducation": o.get("hEducation", "Certifications"),
        "hAchievements": o.get("hAchievements", "Awards & Recognition"),
        "hTestimonials": o.get("hTestimonials", "Client Reviews"),
        "contactHeading": o.get("contactHeading", "Get in touch"),
        "contactText": o.get("contactText", "Tell us about your needs and our team will reply within 24 hours."),
    }}


SAMPLES = [
    _biz("nexus-digital", "aurora", "modern", "Nexus Digital", "Full-Service Marketing Agency",
         _img("1460925895917-afdab827c52f"), "Welcome to", "Get a Free Audit",
         "We help brands grow online with data-driven marketing that delivers real, measurable results.",
         "Nexus Digital is a full-service agency of strategists, designers and developers. Since 2013 we've helped 200+ brands grow their traffic, leads and revenue through smart, measurable campaigns.",
         _stat(("450+", "Projects"), ("200+", "Clients"), ("28", "Team"), ("11", "Years")),
         _svc(("fa-magnifying-glass", "SEO", "Rank higher and capture high-intent traffic."),
              ("fa-bullhorn", "Paid Ads", "Profitable Google & Meta ad campaigns."),
              ("fa-share-nodes", "Social Media", "Content and community that converts."),
              ("fa-pen-ruler", "Web Design", "Fast, beautiful, high-converting websites."),
              ("fa-envelope-open-text", "Email Marketing", "Automations that nurture and sell."),
              ("fa-chart-line", "Analytics", "Clear reporting and growth strategy.")),
         WHY,
         _proj(("Retail Brand Relaunch", "Branding", _img("1432888498266-38ffec3eaf0a"), "+180% online revenue in 6 months."),
               ("SaaS Lead Engine", "PPC", _img("1557804506-669a67965ba0"), "Cut cost-per-lead by 42%."),
               ("Local SEO Domination", "SEO", _img("1556761175-b413da4baf72"), "Top 3 rankings in 30+ keywords."),
               ("E-commerce Funnel", "CRO", _img("1551288049-bebda4e38f71"), "Doubled checkout conversion.")),
         _tl(("Agency Founded", "Started with 3 people", "2013", "Opened our first studio downtown."),
             ("100th Client", "A major milestone", "2017", "Crossed 100 active retainer clients."),
             ("National Expansion", "Three new offices", "2021", "Grew the team to 28 specialists.")),
         _tl(("Google Premier Partner", "Top 3% of agencies", "2022", "Certified across Ads & Analytics."),
             ("Meta Business Partner", "Verified expertise", "2021", "Recognized advertising partner.")),
         _ach(("fa-trophy", "Agency of the Year", "2023"), ("fa-award", "Top 50 Agencies", "MarketingPro"), ("fa-medal", "Best Campaign", "Ad Awards")),
         _tst(("Nexus tripled our qualified leads in one quarter. Truly data-driven.", "Sarah Chen", "CEO, FinEdge", "https://i.pravatar.cc/100?img=45"),
              ("Professional, transparent and effective. Our best marketing decision.", "Mark Davis", "Founder, Loop", "https://i.pravatar.cc/100?img=12")),
         "hello@nexusdigital.com", "+1 (555) 240-1180", "New York, USA", "Mon–Fri · 9am–6pm", "Established 2013"),

    _biz("bella-vista", "noir", "elegant", "Bella Vista", "Authentic Italian Fine Dining",
         _img("1414235077428-338989a2e8c0"), "Welcome to", "Reserve a Table",
         "A timeless Italian dining experience — handmade pasta, fine wine and warm hospitality in the heart of the city.",
         "For over two decades Bella Vista has served authentic Italian cuisine crafted from family recipes and the freshest seasonal ingredients. Every dish tells a story of tradition and passion.",
         _stat(("20+", "Years"), ("120", "Seats"), ("45", "Dishes"), ("4.9", "Rating")),
         _svc(("fa-utensils", "Fine Dining", "Multi-course menus crafted by our head chef."),
              ("fa-champagne-glasses", "Private Events", "Weddings, parties and corporate dinners."),
              ("fa-truck", "Catering", "Bring the Bella Vista experience to you.")),
         _skl(("Authentic Recipes", 99), ("Fresh Ingredients", 98), ("Service Quality", 97), ("Wine Pairing", 95)),
         _proj(("Truffle Risotto", "Signature", _img("1476124369491-e7addf5db371"), "Our guest-favourite dish."),
               ("Handmade Pasta", "Kitchen", _img("1473093295043-cdd812d0e601"), "Rolled fresh every morning."),
               ("Dessert Selection", "Pastry", _img("1551024601-bec78aea704b"), "Classic Italian sweets."),
               ("Seasonal Plates", "Menu", _img("1565299624946-b28f40a0ae38"), "Changing with the seasons.")),
         _tl(("Doors Opened", "A small family trattoria", "2003", "Founded by the Rossi family."),
             ("Michelin Recommended", "Critical acclaim", "2018", "Added to the Michelin guide."),
             ("New Wine Cellar", "300+ labels", "2022", "One of the city's finest cellars.")),
         _tl(("Food Safety Excellence", "5-star hygiene", "2023", "Top food-safety rating."),
             ("Sommelier Certified", "Wine expertise", "2020", "In-house certified sommelier.")),
         _ach(("fa-trophy", "Best Italian Restaurant", "2023"), ("fa-award", "Michelin Recommended", "Guide"), ("fa-medal", "Diners' Choice", "OpenTable")),
         _tst(("The finest Italian meal we've had outside of Italy. Impeccable service.", "Giulia M.", "Guest", "https://i.pravatar.cc/100?img=47"),
              ("A perfect anniversary dinner. Every dish was a masterpiece.", "Henry W.", "Guest", "https://i.pravatar.cc/100?img=51")),
         "reservations@bellavista.com", "+1 (555) 770-2200", "Florence Ave, Chicago", "Tue–Sun · 5pm–11pm", "Established 2003",
         hServices="What We Offer", hWork="Our Menu", hSkills="Why Dine With Us",
         contactText="Reserve a table or ask about private events — we'll respond within a few hours.",
         resumeText="View Menu"),

    _biz("prime-estates", "royal", "split", "Prime Estates", "Premium Real Estate Agency",
         _img("1556742502-ec7c0e9f34b1"), "Welcome to", "Book a Viewing",
         "Helping families and investors find the perfect property with honest advice and white-glove service.",
         "Prime Estates is a boutique real-estate agency specializing in luxury homes and smart investments. Our agents combine deep local knowledge with a client-first approach.",
         _stat(("1.2K+", "Properties Sold"), ("950+", "Happy Clients"), ("18", "Agents"), ("15", "Years")),
         _svc(("fa-house", "Buy a Home", "Curated listings matched to your needs."),
              ("fa-tags", "Sell a Property", "Maximum value with expert marketing."),
              ("fa-key", "Rentals", "Verified rentals for every budget."),
              ("fa-building", "Property Management", "Stress-free management for owners.")),
         _skl(("Client Satisfaction", 98), ("Avg. Sale Speed", 94), ("Negotiation Success", 96), ("Repeat & Referrals", 93)),
         _proj(("Lakeside Villa", "Luxury", _img("1564013799919-ab600027ffc6"), "Sold above asking in 9 days."),
               ("Downtown Penthouse", "Apartment", _img("1545324418-cc1a3fa10c00"), "Premium city-centre living."),
               ("Suburban Family Home", "Residential", _img("1570129477492-45c003edd2be"), "Perfect for growing families."),
               ("Modern Townhouse", "New Build", _img("1512917774080-9991f1c4c750"), "Contemporary design and finish.")),
         _tl(("Agency Founded", "Two agents, one office", "2009", "Built on trust and referrals."),
             ("$500M in Sales", "Major milestone", "2019", "Crossed half a billion in transactions."),
             ("Luxury Division", "New premium arm", "2022", "Dedicated luxury property team.")),
         _tl(("Licensed & Bonded", "Fully accredited", "—", "Registered real-estate brokerage."),
             ("Realtor® Certified", "Professional standard", "—", "Members of the national association.")),
         _ach(("fa-trophy", "Top Agency", "2023"), ("fa-award", "Best in Service", "RealtyAwards"), ("fa-medal", "5-Star Rated", "Google")),
         _tst(("They sold our home in under two weeks above asking. Outstanding.", "The Patels", "Sellers", "https://i.pravatar.cc/100?img=32"),
              ("Found us our dream home and made it stress-free. Highly recommend.", "James L.", "Buyer", "https://i.pravatar.cc/100?img=15")),
         "contact@primeestates.com", "+1 (555) 330-4400", "Beverly Hills, CA", "Mon–Sat · 9am–7pm", "Established 2009",
         hWork="Featured Listings", hSkills="Why Choose Prime"),

    _biz("sterling-law", "mono", "classic", "Sterling & Co.", "Corporate & Commercial Law Firm",
         _img("1551288049-bebda4e38f71"), "Welcome to", "Free Consultation",
         "Trusted legal counsel for businesses and individuals — clear advice, strong representation, real results.",
         "Sterling & Co. is a full-service law firm with decades of combined experience. We deliver pragmatic, results-focused legal solutions across corporate, commercial and dispute matters.",
         _stat(("2K+", "Cases Won"), ("600+", "Clients"), ("24", "Attorneys"), ("30", "Years")),
         _svc(("fa-scale-balanced", "Corporate Law", "Formation, M&A, governance and contracts."),
              ("fa-gavel", "Litigation", "Assertive representation in disputes."),
              ("fa-file-contract", "Commercial Law", "Protect and grow your business interests."),
              ("fa-people-roof", "Family Law", "Compassionate counsel when it matters.")),
         _skl(("Case Success Rate", 97), ("Client Retention", 96), ("Response Time", 95), ("Confidentiality", 100)),
         _proj(("Corporate Merger", "Corporate", _img("1450101499163-c8848c66ca85"), "$120M cross-border deal closed."),
               ("Contract Dispute", "Litigation", _img("1589829545856-d10d557cf95f"), "Favourable settlement secured."),
               ("Startup Counsel", "Advisory", _img("1521791136064-7986c2920216"), "From incorporation to Series A."),
               ("IP Protection", "Commercial", _img("1505664194779-8beaceb93744"), "Safeguarded key trademarks.")),
         _tl(("Firm Established", "Founded by two partners", "1994", "Built on integrity and results."),
             ("1,000th Case", "Proven track record", "2012", "A landmark for the firm."),
             ("New Practice Areas", "Expanded services", "2020", "Added IP and tech law teams.")),
         _tl(("Bar Association", "Members in good standing", "—", "Admitted to practice in all courts."),
             ("ISO 27001", "Information security", "2021", "Certified data protection.")),
         _ach(("fa-trophy", "Law Firm of the Year", "2023"), ("fa-award", "Top Rated Attorneys", "Legal500"), ("fa-medal", "Client Choice", "2022")),
         _tst(("Sterling guided our acquisition flawlessly. Sharp, responsive, trustworthy.", "Robert M.", "CEO", "https://i.pravatar.cc/100?img=53"),
              ("They protected our business when it mattered most. Truly exceptional.", "Anita K.", "Founder", "https://i.pravatar.cc/100?img=27")),
         "office@sterlinglaw.com", "+1 (555) 118-9000", "Wall St, New York", "Mon–Fri · 8am–6pm", "Established 1994",
         hWork="Notable Cases", hSkills="Why Clients Trust Us", hTestimonials="What Our Clients Say"),

    _biz("buildright", "forest", "bold", "BuildRight", "Construction & Architecture",
         _img("1503387762-592deb58ef4e"), "Welcome to", "Request a Quote",
         "Building landmarks that last — residential, commercial and industrial projects delivered on time, on budget.",
         "BuildRight is an award-winning construction and architecture firm. From concept to completion we combine craftsmanship, modern engineering and sustainable design.",
         _stat(("780+", "Projects"), ("320", "Clients"), ("150", "Workforce"), ("22", "Years")),
         _svc(("fa-house-chimney", "Residential", "Custom homes built to the highest standard."),
              ("fa-building", "Commercial", "Offices, retail and mixed-use developments."),
              ("fa-helmet-safety", "Renovation", "Modern upgrades and structural work."),
              ("fa-compass-drafting", "Architecture & Design", "Concept design and planning.")),
         _skl(("On-Time Completion", 96), ("Safety Record", 99), ("Budget Accuracy", 95), ("Client Satisfaction", 97)),
         _proj(("City Office Tower", "Commercial", _img("1486406146926-c627a92ad1ab"), "18-storey landmark build."),
               ("Lakeside Residences", "Residential", _img("1487958449943-2429e8be8625"), "42 premium family homes."),
               ("Modern Warehouse", "Industrial", _img("1581094794329-c8112a89af12"), "120,000 sq ft logistics hub."),
               ("Heritage Restoration", "Renovation", _img("1503387762-592deb58ef4e"), "Restored a 1920s facade.")),
         _tl(("Company Founded", "A small contracting crew", "2002", "Started with residential builds."),
             ("First Commercial Tower", "Major milestone", "2014", "Delivered our first high-rise."),
             ("Green Building Arm", "Sustainable focus", "2021", "Launched eco-construction division.")),
         _tl(("ISO 9001 Certified", "Quality management", "2018", "Independently audited quality."),
             ("Safety Accredited", "Zero-harm standard", "2020", "Industry safety certification.")),
         _ach(("fa-trophy", "Best Commercial Build", "2023"), ("fa-award", "Excellence in Safety", "BuildAwards"), ("fa-medal", "Green Builder", "2022")),
         _tst(("BuildRight delivered our office on time and exactly to spec. Brilliant team.", "Daniel R.", "Developer", "https://i.pravatar.cc/100?img=13"),
              ("Quality craftsmanship and total transparency from start to finish.", "Megan F.", "Homeowner", "https://i.pravatar.cc/100?img=24")),
         "projects@buildright.com", "+1 (555) 905-3100", "Austin, Texas", "Mon–Sat · 7am–5pm", "Established 2002",
         hWork="Our Projects", hSkills="Why Build With Us"),

    _biz("medicare-plus", "ocean", "minimal", "MediCare Plus", "Family Health & Dental Clinic",
         _img("1629909613654-28e377c37b09"), "Welcome to", "Book an Appointment",
         "Compassionate, modern healthcare for the whole family — gentle care and trusted expertise under one roof.",
         "MediCare Plus is a multi-specialty clinic dedicated to gentle, patient-first care. Our experienced doctors use modern technology to keep your family healthy and smiling.",
         _stat(("25K+", "Patients"), ("12", "Specialists"), ("6", "Departments"), ("16", "Years")),
         _svc(("fa-stethoscope", "General Medicine", "Checkups, diagnosis and ongoing care."),
              ("fa-tooth", "Dental Care", "Gentle dentistry for all ages."),
              ("fa-baby", "Pediatrics", "Caring health services for children."),
              ("fa-microscope", "Diagnostics", "On-site lab and imaging.")),
         _skl(("Patient Satisfaction", 99), ("Appointment Speed", 95), ("Modern Equipment", 98), ("Follow-up Care", 96)),
         _proj(("Smile Makeovers", "Dental", _img("1606811841689-23dfddce3e95"), "Confident, healthy smiles."),
               ("Pediatric Wing", "Facility", _img("1588776814546-1ffcf47267a5"), "Gentle care for kids."),
               ("Diagnostic Lab", "Technology", _img("1612349317150-e413f6a5b16d"), "Fast, accurate results."),
               ("Modern Clinic", "Facility", _img("1629909613654-28e377c37b09"), "State-of-the-art rooms.")),
         _tl(("Clinic Opened", "A single-doctor practice", "2008", "Founded on patient-first care."),
             ("New Dental Wing", "Expanded services", "2016", "Added full dental department."),
             ("25,000 Patients", "Trusted by the community", "2023", "A milestone we're proud of.")),
         _tl(("Accredited Clinic", "National health board", "—", "Meets the highest care standards."),
             ("Certified Specialists", "Board-certified team", "—", "Experienced, qualified doctors.")),
         _ach(("fa-trophy", "Top Rated Clinic", "2023"), ("fa-award", "Excellence in Care", "Health Board"), ("fa-medal", "Patient Choice", "2022")),
         _tst(("The team is gentle, professional and genuinely caring. Highly recommend.", "Anita K.", "Patient", "https://i.pravatar.cc/100?img=27"),
              ("Best dental experience I've had. Painless and friendly throughout.", "Robert M.", "Patient", "https://i.pravatar.cc/100?img=53")),
         "care@medicareplus.com", "+1 (555) 660-7700", "London, UK", "Mon–Sat · 8am–8pm", "Established 2008",
         hServices="Our Departments", hWork="Inside Our Clinic", hSkills="Why Patients Trust Us", hTestimonials="Patient Stories"),

    _biz("luxe-spa", "coral", "centered", "Luxe Salon & Spa", "Beauty, Hair & Wellness",
         _img("1560066984-138dadb4c035"), "Welcome to", "Book Your Visit",
         "Relax, refresh and glow — premium beauty and wellness treatments in a calm, luxurious setting.",
         "Luxe Salon & Spa is your sanctuary for beauty and relaxation. Our expert stylists and therapists deliver personalised treatments that leave you looking and feeling your best.",
         _stat(("15K+", "Happy Clients"), ("30+", "Treatments"), ("14", "Specialists"), ("10", "Years")),
         _svc(("fa-scissors", "Hair Styling", "Cuts, colour and styling by experts."),
              ("fa-spa", "Skincare & Facials", "Glow-boosting treatments for every skin."),
              ("fa-hand-sparkles", "Massage & Spa", "Relaxing therapies to de-stress."),
              ("fa-hand", "Nails & Beauty", "Manicures, pedicures and more.")),
         _skl(("Client Satisfaction", 99), ("Repeat Clients", 95), ("Hygiene Standards", 100), ("On-Time Service", 96)),
         _proj(("Bridal Glam", "Hair & Makeup", _img("1560066984-138dadb4c035"), "Look stunning on your big day."),
               ("Signature Facial", "Skincare", _img("1570172619644-dfd03ed5d881"), "Radiant, refreshed skin."),
               ("Relax Massage", "Spa", _img("1600334089648-b0d9d3028eb2"), "Melt your stress away."),
               ("Nail Artistry", "Nails", _img("1604654894610-df63bc536371"), "Beautiful, lasting designs.")),
         _tl(("Salon Opened", "One chair, big dreams", "2014", "Started as a small studio."),
             ("Spa Wing Added", "Full wellness offering", "2019", "Expanded into massage & spa."),
             ("15,000 Clients", "A loyal community", "2023", "Grateful for our wonderful clients.")),
         _tl(("Certified Therapists", "Qualified professionals", "—", "Trained and certified team."),
             ("Hygiene Excellence", "5-star standard", "2023", "Top sanitation rating.")),
         _ach(("fa-trophy", "Best Spa", "2023"), ("fa-award", "Beauty Excellence", "GlowAwards"), ("fa-medal", "Customer Choice", "2022")),
         _tst(("I always leave feeling amazing. The team is so talented and kind.", "Priya S.", "Regular Client", "https://i.pravatar.cc/100?img=44"),
              ("The bridal package was perfect — I felt like a queen!", "Emma L.", "Bride", "https://i.pravatar.cc/100?img=49")),
         "hello@luxespa.com", "+1 (555) 220-8800", "Miami, USA", "Mon–Sun · 10am–8pm", "Established 2014",
         hServices="Our Treatments", hWork="Our Work", hSkills="Why Visit Luxe"),

    _biz("apex-consulting", "sunset", "wide", "Apex Consulting", "Business & Management Consulting",
         _img("1542744173-8e7e53415bb0"), "Welcome to", "Schedule a Call",
         "We help companies solve their toughest challenges and unlock sustainable, profitable growth.",
         "Apex Consulting partners with leaders to drive strategy, operations and transformation. Our consultants bring sharp analysis and practical execution to every engagement.",
         _stat(("600+", "Engagements"), ("180", "Clients"), ("40", "Consultants"), ("14", "Years")),
         _svc(("fa-chess", "Strategy", "Clarity and direction for sustainable growth."),
              ("fa-gears", "Operations", "Streamline processes and cut costs."),
              ("fa-coins", "Finance Advisory", "Smarter planning and capital decisions."),
              ("fa-users-gear", "People & Change", "Build teams and lead transformation.")),
         _skl(("Project ROI", 97), ("Client Retention", 95), ("On-Time Delivery", 96), ("Stakeholder Buy-in", 94)),
         _proj(("Operational Turnaround", "Operations", _img("1454165804606-c3d57bc86b40"), "Saved a client $4M annually."),
               ("Growth Strategy", "Strategy", _img("1552664730-d307ca884978"), "Entered 3 new markets."),
               ("Digital Transformation", "Change", _img("1517245386807-bb43f82c33c4"), "Modernised legacy operations."),
               ("Cost Optimisation", "Finance", _img("1460925895917-afdab827c52f"), "22% reduction in overhead.")),
         _tl(("Firm Founded", "Two ex-industry leaders", "2010", "Built on results, not slides."),
             ("Global Clients", "Cross-border work", "2018", "Engagements across 12 countries."),
             ("Innovation Lab", "New offering", "2022", "Launched a data & AI practice.")),
         _tl(("Certified Consultants", "Recognised expertise", "—", "Accredited management consultants."),
             ("ISO 9001", "Quality assured", "2019", "Audited delivery standards.")),
         _ach(("fa-trophy", "Consultancy of the Year", "2023"), ("fa-award", "Top Advisory Firm", "BizWeekly"), ("fa-medal", "Excellence Award", "2022")),
         _tst(("Apex gave us a clear plan and helped us execute it. Real impact.", "Jennifer L.", "COO", "https://i.pravatar.cc/100?img=20"),
              ("Sharp thinking and hands-on support. They feel like part of our team.", "Tom B.", "CEO", "https://i.pravatar.cc/100?img=15")),
         "connect@apexconsulting.com", "+1 (555) 440-1200", "Boston, USA", "Mon–Fri · 9am–6pm", "Established 2010",
         hWork="Case Studies", hSkills="Why Apex"),

    _biz("urban-threads", "candy", "showcase", "Urban Threads", "Modern Fashion & Lifestyle Store",
         _img("1441986300917-64674bd600d8"), "Welcome to", "Shop Now",
         "Curated fashion for everyday confidence — fresh styles, quality fabrics and a personal touch.",
         "Urban Threads is a modern lifestyle boutique offering handpicked clothing and accessories. We blend trend and comfort to help you express your style, effortlessly.",
         _stat(("5K+", "Products"), ("40K+", "Orders"), ("25K+", "Customers"), ("9", "Years")),
         _svc(("fa-shirt", "Men's Fashion", "Smart, casual and everything between."),
              ("fa-vest", "Women's Fashion", "Curated styles for every occasion."),
              ("fa-bag-shopping", "Accessories", "Bags, jewellery and finishing touches."),
              ("fa-truck-fast", "Fast Delivery", "Quick shipping and easy returns.")),
         _skl(("Customer Satisfaction", 98), ("Repeat Buyers", 90), ("On-Time Shipping", 96), ("Product Quality", 97)),
         _proj(("Summer Collection", "Lookbook", _img("1483985988355-763728e1935b"), "Fresh styles for the season."),
               ("Street Edit", "Men", _img("1490481651871-ab68de25d43d"), "Urban looks that turn heads."),
               ("Evening Wear", "Women", _img("1445205170230-053b83016050"), "Elegant pieces for nights out."),
               ("Accessories Drop", "Accessories", _img("1611652022419-a9419f74343d"), "The perfect finishing touch.")),
         _tl(("Store Opened", "One small boutique", "2015", "Started in a corner shop."),
             ("Online Launch", "Going digital", "2019", "Shipped nationwide for the first time."),
             ("40,000 Orders", "Growing community", "2023", "Thank you to our loyal customers.")),
         _tl(("Trusted Seller", "Verified store", "—", "Top-rated across review platforms."),
             ("Sustainable Sourcing", "Ethical fabrics", "2022", "Committed to responsible fashion.")),
         _ach(("fa-trophy", "Best Boutique", "2023"), ("fa-award", "Customer Choice", "ShopAwards"), ("fa-medal", "5-Star Rated", "Trustpilot")),
         _tst(("Gorgeous clothes and the fastest delivery. My favourite store!", "Olivia P.", "Customer", "https://i.pravatar.cc/100?img=32"),
              ("Quality is amazing and the styling help is a lovely touch.", "Aman G.", "Customer", "https://i.pravatar.cc/100?img=13")),
         "support@urbanthreads.com", "+1 (555) 770-6600", "Los Angeles, USA", "Daily · 10am–9pm", "Established 2015",
         hServices="Shop By Category", hWork="Collections", hSkills="Why Shop With Us", hTestimonials="Customer Love"),

    _biz("cloudpeak", "minimal", "compact", "CloudPeak", "Software & IT Solutions",
         _img("1518770660439-4636190af475"), "Welcome to", "Start a Project",
         "We design and build reliable software, cloud and security solutions that help businesses scale with confidence.",
         "CloudPeak is a software and IT company delivering custom apps, cloud infrastructure and cybersecurity. We turn complex problems into clean, scalable technology.",
         _stat(("300+", "Projects"), ("120", "Clients"), ("60", "Engineers"), ("10", "Years")),
         _svc(("fa-code", "Software Development", "Custom web and mobile applications."),
              ("fa-cloud", "Cloud Solutions", "Scalable, secure cloud infrastructure."),
              ("fa-shield-halved", "Cybersecurity", "Protect your data and systems."),
              ("fa-headset", "IT Support", "Reliable, responsive managed support.")),
         _skl(("Uptime Guarantee", 99), ("On-Time Delivery", 96), ("Client Retention", 95), ("Security Standards", 98)),
         _proj(("Enterprise Platform", "Software", _img("1498050108023-c5249f4df085"), "Serves 2M+ users daily."),
               ("Cloud Migration", "Cloud", _img("1517180102446-f3ece451e9d8"), "Zero-downtime transition."),
               ("Mobile Banking App", "Mobile", _img("1461749280684-dccba630e2f6"), "Secure, 5-star rated app."),
               ("Analytics Dashboard", "Software", _img("1551288049-bebda4e38f71"), "Real-time business insights.")),
         _tl(("Company Founded", "A few engineers", "2014", "Started building for startups."),
             ("Cloud Division", "New capability", "2018", "Became a certified cloud partner."),
             ("Security Practice", "Expanded services", "2022", "Added a dedicated security team.")),
         _tl(("ISO 27001", "Information security", "2021", "Certified security management."),
             ("Cloud Partner", "Verified expertise", "2020", "Recognised cloud solutions partner.")),
         _ach(("fa-trophy", "Top IT Company", "2023"), ("fa-award", "Best Software Team", "TechAwards"), ("fa-medal", "Innovation Prize", "2022")),
         _tst(("CloudPeak rebuilt our platform and it's never been faster or safer.", "Jessica Park", "CTO", "https://i.pravatar.cc/100?img=32"),
              ("Reliable, skilled and easy to work with. A true technology partner.", "Ryan C.", "Founder", "https://i.pravatar.cc/100?img=33")),
         "hello@cloudpeak.io", "+1 (555) 980-4500", "Seattle, USA", "Mon–Fri · 9am–6pm", "Established 2014",
         hWork="Our Solutions", hSkills="Why CloudPeak", hServices="What We Build"),

    _biz("wander-travel", "ocean", "stack", "Wanderlust Travel", "Tours & Travel Agency",
         _img("1488646953014-85cb44e25828"), "Welcome to", "Plan My Trip",
         "Unforgettable journeys, expertly planned — handpicked destinations, seamless trips and prices that smile back.",
         "Wanderlust Travel has been crafting dream holidays for over a decade. From honeymoons to family adventures, our travel experts handle every detail so you can simply explore.",
         _stat(("1.5K+", "Trips Planned"), ("60+", "Destinations"), ("12K+", "Travellers"), ("12", "Years")),
         _svc(("fa-earth-americas", "Tour Packages", "Curated trips to the world's best spots."),
              ("fa-plane", "Flights & Hotels", "Best fares and handpicked stays."),
              ("fa-passport", "Visa Assistance", "Hassle-free paperwork and support."),
              ("fa-route", "Custom Itineraries", "Trips designed around you.")),
         WHY,
         _proj(("Bali Escape", "Asia", _img("1537996194471-e657df975ab4"), "7 nights of island paradise."),
               ("European Tour", "Europe", _img("1528181304800-259b08848526"), "5 countries, endless memories."),
               ("Safari Adventure", "Africa", _img("1547970810-dc1eac37d174"), "Up close with the wild."),
               ("Maldives Honeymoon", "Beach", _img("1514282401047-d79a71a590e8"), "Romance over turquoise water.")),
         _tl(("Agency Founded", "Two travel lovers", "2012", "Started planning trips for friends."),
             ("10,000th Traveller", "A happy milestone", "2020", "Sent our 10,000th guest abroad.")),
         _tl(("IATA Accredited", "Trusted agency", "—", "Officially accredited travel agent."),
             ("Award-Winning", "Top operator", "2022", "Recognised for service excellence.")),
         _ach(("fa-trophy", "Best Travel Agency", "2023"), ("fa-award", "Customer Choice", "TripAwards"), ("fa-medal", "5-Star Rated", "Google")),
         _tst(("Best holiday of our lives — every detail was perfect.", "The Sharmas", "Travellers", "https://i.pravatar.cc/100?img=45"),
              ("Stress-free planning and amazing value. Highly recommend!", "Olivia P.", "Traveller", "https://i.pravatar.cc/100?img=32")),
         "hello@wanderlust.com", "+1 (555) 310-2020", "Sydney, Australia", "Mon–Sat · 9am–7pm", "Established 2012",
         hWork="Popular Trips", hSkills="Why Travel With Us"),

    _biz("ironcore-gym", "mono", "duo", "IronCore Fitness", "Strength & Conditioning Gym",
         _img("1534438327276-14e5300c3a48"), "Welcome to", "Start Training",
         "Build strength, burn fat and feel unstoppable — expert coaching and a community that pushes you further.",
         "IronCore is more than a gym — it's a community. With expert trainers, modern equipment and proven programs, we help members of every level reach their goals.",
         _stat(("2K+", "Members"), ("25", "Trainers"), ("40+", "Classes"), ("8", "Years")),
         _svc(("fa-dumbbell", "Strength Training", "Build muscle with structured programs."),
              ("fa-fire", "HIIT & Cardio", "High-energy fat-burning sessions."),
              ("fa-heart-pulse", "Personal Coaching", "1-on-1 plans tailored to you."),
              ("fa-people-group", "Group Classes", "Train together, stay motivated.")),
         _skl(("Member Results", 97), ("Trainer Expertise", 98), ("Equipment Quality", 96), ("Class Variety", 94)),
         _proj(("12-Week Shred", "Program", _img("1571019613454-1cb2f99b2d8b"), "Real member transformations."),
               ("Powerlifting Club", "Strength", _img("1534438327276-14e5300c3a48"), "Build serious strength."),
               ("HIIT Bootcamp", "Cardio", _img("1517836357463-d25dfeac3438"), "Burn, sweat, repeat."),
               ("Mobility & Recovery", "Wellness", _img("1581009146145-b5ef050c2e1e"), "Move better, feel better.")),
         _tl(("Doors Opened", "One small studio", "2016", "Started with a handful of members."),
             ("2,000 Members", "Growing strong", "2023", "A thriving fitness community.")),
         _tl(("Certified Trainers", "Qualified team", "—", "NASM & ACE certified coaches."),
             ("Safety Accredited", "Top standards", "2022", "Certified safe training facility.")),
         _ach(("fa-trophy", "Best Gym in Town", "2023"), ("fa-award", "Top Trainers", "FitAwards"), ("fa-medal", "Community Choice", "2022")),
         _tst(("Down 30lbs and stronger than ever. The coaches are incredible.", "Chris D.", "Member", "https://i.pravatar.cc/100?img=52"),
              ("Best gym community I've been part of. Motivating every single day.", "Megan F.", "Member", "https://i.pravatar.cc/100?img=24")),
         "train@ironcore.com", "+1 (555) 660-1010", "Denver, USA", "Daily · 5am–11pm", "Established 2016",
         hWork="Our Programs", hSkills="Why Train Here"),

    _biz("brew-bean", "sunset", "rounded", "Brew & Bean", "Specialty Coffee Café",
         _img("1495474472287-4d71bcdd2085"), "Welcome to", "Visit Us",
         "Lovingly roasted coffee, fresh bakes and a cosy corner to call your own — your daily ritual, perfected.",
         "Brew & Bean is a neighbourhood café serving ethically sourced, freshly roasted coffee and homemade treats. Come for the coffee, stay for the warmth.",
         _stat(("50K+", "Cups Served"), ("18", "Blends"), ("4.9", "Rating"), ("7", "Years")),
         _svc(("fa-mug-saucer", "Specialty Coffee", "Single-origin and signature blends."),
              ("fa-cookie-bite", "Fresh Bakes", "Pastries and cakes made daily."),
              ("fa-leaf", "Ethically Sourced", "Beans from sustainable farms.")),
         _skl(("Coffee Quality", 99), ("Friendly Service", 98), ("Cosy Atmosphere", 97), ("Freshness", 99)),
         _proj(("Signature Latte", "Coffee", _img("1504674900247-0877df9cc836"), "Our most-loved cup."),
               ("Morning Bakes", "Bakery", _img("1445116572660-236099ec97a0"), "Warm from the oven."),
               ("Cold Brew", "Coffee", _img("1461023058943-07fcbe16d735"), "Smooth and refreshing."),
               ("Café Corner", "Our Space", _img("1447933601403-0c6688de566e"), "Your cosy second home.")),
         _tl(("Café Opened", "A tiny coffee cart", "2017", "Started serving the morning crowd."),
             ("New Roastery", "Roasting in-house", "2021", "Fresh beans, every day.")),
         _tl(("Fair Trade Certified", "Ethical sourcing", "2020", "Certified sustainable beans."),
             ("Hygiene Excellence", "5-star rated", "2023", "Top food-safety standard.")),
         _ach(("fa-trophy", "Best Café", "2023"), ("fa-award", "Best Coffee", "FoodieAwards"), ("fa-medal", "Local Favourite", "2022")),
         _tst(("The best coffee in the city, hands down. And the staff are lovely.", "Daniel R.", "Regular", "https://i.pravatar.cc/100?img=13"),
              ("My favourite spot to work and unwind. Always warm and welcoming.", "Priya S.", "Customer", "https://i.pravatar.cc/100?img=44")),
         "hello@brewandbean.com", "+1 (555) 220-3030", "Portland, USA", "Daily · 7am–8pm", "Established 2017",
         hServices="What We Serve", hWork="Menu Highlights", hSkills="Why Visit Us"),

    _biz("lens-studio", "noir", "spotlight", "Lens Studio", "Photography & Film Studio",
         _img("1452587925148-ce544e77e70d"), "Welcome to", "Book a Shoot",
         "Capturing your story with cinematic style — portraits, weddings and brand films that last a lifetime.",
         "Lens Studio is a creative photography and film house. We blend artistry and technical mastery to create images and films that move people.",
         _stat(("900+", "Shoots"), ("15K+", "Photos"), ("4.9", "Rating"), ("10", "Years")),
         _svc(("fa-camera-retro", "Portraits", "Striking portraits that capture you."),
              ("fa-ring", "Weddings", "Timeless coverage of your big day."),
              ("fa-film", "Brand Films", "Cinematic video for brands.")),
         _skl(("Creativity", 99), ("Technical Skill", 97), ("Client Experience", 98), ("Editing", 96)),
         _proj(("Mountain Series", "Landscape", _img("1506905925346-21bda4d32df4"), "Nature in its finest light."),
               ("Studio Portraits", "Portrait", _img("1492691527719-9d1e07e534b4"), "Bold, expressive frames."),
               ("Wedding Story", "Wedding", _img("1519741497674-611481863552"), "Love, beautifully told."),
               ("Editorial Shoot", "Fashion", _img("1500648767791-00dcc994a43e"), "Magazine-worthy imagery.")),
         _tl(("Studio Founded", "One camera, big vision", "2014", "Started shooting portraits."),
             ("Award-Winning Work", "Recognised craft", "2021", "Published in three magazines.")),
         _tl(("Certified Pro", "Industry standard", "—", "Accredited professional photographer."),
             ("Featured Artist", "National press", "2022", "Showcased in major publications.")),
         _ach(("fa-trophy", "Photographer of the Year", "2023"), ("fa-award", "Top Wedding Photos", "WPJA"), ("fa-medal", "Visual Excellence", "2022")),
         _tst(("They captured our wedding perfectly — every photo tells a story.", "Emma & Jake", "Newlyweds", "https://i.pravatar.cc/100?img=49"),
              ("Absolute professionals. The brand film exceeded our expectations.", "Mark D.", "Founder", "https://i.pravatar.cc/100?img=12")),
         "studio@lensstudio.com", "+1 (555) 770-4040", "Vancouver, Canada", "By appointment", "Established 2014",
         hWork="Our Portfolio", hSkills="Why Choose Lens"),

    _biz("grand-events", "candy", "frame", "Grand Events", "Event Planning & Weddings",
         _img("1519225421980-715cb0215aed"), "Welcome to", "Plan My Event",
         "From dream weddings to flawless corporate galas — we turn your vision into an unforgettable celebration.",
         "Grand Events is a full-service event planning company. Our creative team handles everything — design, vendors, logistics — so your day is perfect and stress-free.",
         _stat(("800+", "Events"), ("500+", "Weddings"), ("4.9", "Rating"), ("11", "Years")),
         _svc(("fa-ring", "Weddings", "Magical weddings, beautifully planned."),
              ("fa-champagne-glasses", "Corporate Events", "Polished, professional gatherings."),
              ("fa-cake-candles", "Private Parties", "Birthdays, anniversaries and more."),
              ("fa-gift", "Full Coordination", "We handle every last detail.")),
         WHY,
         _proj(("Garden Wedding", "Wedding", _img("1464366400600-7168b8af9bc3"), "300 guests, zero stress."),
               ("Corporate Gala", "Corporate", _img("1530103862676-de8c9debad1d"), "An evening to remember."),
               ("Birthday Bash", "Party", _img("1511795409834-ef04bbd61622"), "Celebration done right."),
               ("Outdoor Reception", "Wedding", _img("1465495976277-4387d4b0b4c6"), "Beauty under the stars.")),
         _tl(("Company Founded", "A passion for celebrations", "2013", "Planned our first wedding."),
             ("500th Wedding", "A proud milestone", "2022", "Half a thousand happy couples.")),
         _tl(("Certified Planners", "Qualified team", "—", "Accredited event professionals."),
             ("Preferred Vendor", "Trusted partner", "2021", "Top venues recommend us.")),
         _ach(("fa-trophy", "Best Event Planner", "2023"), ("fa-award", "Wedding Excellence", "BridalAwards"), ("fa-medal", "Couples' Choice", "2022")),
         _tst(("They made our wedding absolutely magical and completely stress-free.", "Sam & Lee", "Couple", "https://i.pravatar.cc/100?img=26"),
              ("Our corporate gala was flawless. True professionals.", "Jennifer L.", "Director", "https://i.pravatar.cc/100?img=20")),
         "events@grandevents.com", "+1 (555) 440-5050", "Miami, USA", "Mon–Sat · 10am–7pm", "Established 2013",
         hWork="Featured Events", hSkills="Why Choose Grand"),

    _biz("dwell-interiors", "forest", "editorial", "Dwell Interiors", "Interior Design Studio",
         _img("1586023492125-27b2c045efd7"), "Welcome to", "Book a Consultation",
         "Thoughtful interiors that feel like home — beautiful, functional spaces designed around the way you live.",
         "Dwell Interiors is an award-winning design studio creating warm, timeless spaces. From single rooms to full homes, we balance beauty, comfort and function.",
         _stat(("400+", "Projects"), ("250+", "Clients"), ("12", "Designers"), ("13", "Years")),
         _svc(("fa-couch", "Residential Design", "Homes that feel uniquely yours."),
              ("fa-building", "Commercial Spaces", "Workspaces that inspire."),
              ("fa-paintbrush", "Styling & Decor", "The perfect finishing touches.")),
         _skl(("Design Vision", 98), ("On-Budget Delivery", 95), ("Client Satisfaction", 98), ("Attention to Detail", 99)),
         _proj(("Modern Living Room", "Residential", _img("1556742502-ec7c0e9f34b1"), "Warm, minimal, timeless."),
               ("Boutique Office", "Commercial", _img("1513885535751-8b9238bd345a"), "A workspace people love."),
               ("Cosy Bedroom", "Residential", _img("1493809842364-78817add7ffb"), "Calm and inviting."),
               ("Open Kitchen", "Renovation", _img("1505693416388-ac5ce068fe85"), "The heart of the home.")),
         _tl(("Studio Founded", "One designer, big ideas", "2011", "Started with local homes."),
             ("Award-Winning", "Industry recognition", "2020", "Named a top design studio.")),
         _tl(("Certified Designers", "Qualified team", "—", "Accredited interior designers."),
             ("Sustainable Design", "Eco-conscious", "2022", "Committed to greener spaces.")),
         _ach(("fa-trophy", "Design Studio of the Year", "2023"), ("fa-award", "Best Interior", "DesignAwards"), ("fa-medal", "Clients' Choice", "2022")),
         _tst(("They transformed our house into a home we never want to leave.", "The Patels", "Homeowners", "https://i.pravatar.cc/100?img=27"),
              ("Beautiful work, on time and on budget. A joy to work with.", "Robert M.", "Client", "https://i.pravatar.cc/100?img=53")),
         "hello@dwellinteriors.com", "+1 (555) 905-6060", "London, UK", "Mon–Fri · 9am–6pm", "Established 2011",
         hWork="Our Designs", hSkills="Why Dwell"),

    _biz("velocity-motors", "royal", "band", "Velocity Motors", "Premium Car Dealership",
         _img("1503376780353-7e6692767b70"), "Welcome to", "Browse Inventory",
         "Drive your dream — premium new and pre-owned vehicles, honest pricing and service you can trust.",
         "Velocity Motors is a premium dealership offering an exceptional range of vehicles and a no-pressure buying experience. Quality cars, fair deals, lifelong service.",
         _stat(("3K+", "Cars Sold"), ("500+", "In Stock"), ("4.8", "Rating"), ("18", "Years")),
         _svc(("fa-car", "New Vehicles", "The latest models from top brands."),
              ("fa-car-side", "Pre-Owned", "Certified, inspected used cars."),
              ("fa-money-bill-wave", "Easy Financing", "Flexible plans to suit you."),
              ("fa-wrench", "Service & Care", "Expert servicing and warranty.")),
         _skl(("Customer Satisfaction", 97), ("Fair Pricing", 96), ("Vehicle Quality", 98), ("After-Sales Service", 95)),
         _proj(("Luxury Sedan", "New", _img("1552519507-da3b142c6e3d"), "Refined power and comfort."),
               ("Sport Coupe", "Performance", _img("1492144534655-ae79c964c9d7"), "Built for the thrill."),
               ("Family SUV", "New", _img("1494976388531-d1058494cdd8"), "Space, safety and style."),
               ("Certified Pre-Owned", "Used", _img("1583121274602-3e2820c69888"), "Like-new, fully inspected.")),
         _tl(("Dealership Opened", "A small lot", "2006", "Sold our first ten cars."),
             ("3,000 Cars Sold", "Trusted by thousands", "2022", "A milestone built on trust.")),
         _tl(("Authorized Dealer", "Official partner", "—", "Certified by leading brands."),
             ("Quality Assured", "Inspection standard", "2021", "Every car fully checked.")),
         _ach(("fa-trophy", "Top Dealership", "2023"), ("fa-award", "Best Service", "AutoAwards"), ("fa-medal", "Customer Choice", "2022")),
         _tst(("Bought my dream car with zero pressure. Fantastic experience.", "James L.", "Customer", "https://i.pravatar.cc/100?img=15"),
              ("Honest pricing and brilliant after-sales care. Highly recommend.", "Aman G.", "Customer", "https://i.pravatar.cc/100?img=13")),
         "sales@velocitymotors.com", "+1 (555) 330-7070", "Dallas, USA", "Mon–Sat · 9am–8pm", "Established 2006",
         hWork="Featured Vehicles", hSkills="Why Buy From Us"),

    _biz("pawcare-vet", "coral", "clean", "PawCare Clinic", "Veterinary & Pet Care",
         _img("1583337130417-3346a1be7dee"), "Welcome to", "Book an Appointment",
         "Loving care for your best friend — gentle, expert veterinary services to keep your pets happy and healthy.",
         "PawCare is a full-service veterinary clinic run by animal lovers. From routine checkups to emergencies, we treat every pet like family.",
         _stat(("20K+", "Pets Treated"), ("10", "Vets"), ("4.9", "Rating"), ("14", "Years")),
         _svc(("fa-paw", "Wellness Checkups", "Routine care to keep pets healthy."),
              ("fa-syringe", "Vaccinations", "Protect your pet from illness."),
              ("fa-stethoscope", "Surgery & Dental", "Expert procedures and care."),
              ("fa-house-medical", "Emergency Care", "Here when you need us most.")),
         _skl(("Pet Wellbeing", 99), ("Gentle Handling", 98), ("Owner Trust", 98), ("Modern Equipment", 96)),
         _proj(("Puppy Wellness", "Checkup", _img("1450778869180-41d0601e046e"), "A healthy start to life."),
               ("Dental Care", "Treatment", _img("1576201836106-db1758fd1c97"), "Bright, healthy smiles."),
               ("Cat Clinic", "Specialty", _img("1568640347023-a616a30bc3bd"), "Calm, feline-friendly care."),
               ("Happy Patients", "Our Family", _img("1517849845537-4d257902454a"), "Tails wagging since 2009.")),
         _tl(("Clinic Opened", "One caring vet", "2009", "Founded on love for animals."),
             ("20,000 Pets", "A trusted community", "2023", "Proud to serve so many families.")),
         _tl(("Licensed Veterinarians", "Qualified team", "—", "Fully accredited and registered."),
             ("Fear-Free Certified", "Gentle care", "2021", "Stress-free visits for pets.")),
         _ach(("fa-trophy", "Best Vet Clinic", "2023"), ("fa-award", "Compassionate Care", "PetAwards"), ("fa-medal", "5-Star Rated", "Google")),
         _tst(("They treat my dog like their own. Gentle, caring and professional.", "Megan F.", "Pet Owner", "https://i.pravatar.cc/100?img=24"),
              ("Saved my cat in an emergency. Forever grateful to this team.", "Daniel R.", "Pet Owner", "https://i.pravatar.cc/100?img=13")),
         "care@pawcare.com", "+1 (555) 660-8080", "Seattle, USA", "Mon–Sun · 8am–8pm", "Established 2009",
         hServices="Our Services", hWork="Meet Our Patients", hSkills="Why Pet Owners Trust Us"),

    _biz("brightminds", "aurora", "grid", "BrightMinds Academy", "Education & Coaching Institute",
         _img("1503676260728-1c00da094a0b"), "Welcome to", "Enroll Now",
         "Where students thrive — expert teachers, proven methods and personal attention that builds real confidence.",
         "BrightMinds Academy is a results-driven institute helping students excel. With small classes and dedicated mentors, we turn potential into achievement.",
         _stat(("8K+", "Students"), ("95%", "Pass Rate"), ("60", "Educators"), ("15", "Years")),
         _svc(("fa-book-open", "Academic Coaching", "Strong foundations across subjects."),
              ("fa-laptop", "Online Classes", "Learn from anywhere, anytime."),
              ("fa-pen-to-square", "Test Prep", "Ace your exams with confidence."),
              ("fa-user-graduate", "Career Guidance", "Plan a brighter future.")),
         _skl(("Student Results", 98), ("Teaching Quality", 99), ("Parent Satisfaction", 97), ("Personal Attention", 96)),
         _proj(("STEM Program", "Academics", _img("1497486751825-1233686d5d80"), "Hands-on science and maths."),
               ("Online Learning", "Digital", _img("1522202176988-66273c2fd55f"), "Interactive virtual classes."),
               ("Exam Bootcamp", "Test Prep", _img("1571260899304-425eee4c7efc"), "Focused, results-driven prep."),
               ("Student Success", "Our Pride", _img("1524178232363-1fb2b075b655"), "Thousands of bright futures.")),
         _tl(("Academy Founded", "A single classroom", "2009", "Started with 20 students."),
             ("8,000 Students", "Growing community", "2023", "Helping students excel for years.")),
         _tl(("Certified Institute", "Recognised standard", "—", "Accredited education provider."),
             ("Award-Winning Faculty", "Top educators", "2022", "Recognised teaching excellence.")),
         _ach(("fa-trophy", "Best Coaching Institute", "2023"), ("fa-award", "Excellence in Education", "EduAwards"), ("fa-medal", "Parents' Choice", "2022")),
         _tst(("My daughter's grades and confidence soared. Wonderful teachers.", "The Sharmas", "Parents", "https://i.pravatar.cc/100?img=45"),
              ("The best decision for my career. Clear teaching and real results.", "Ryan C.", "Student", "https://i.pravatar.cc/100?img=33")),
         "admissions@brightminds.com", "+1 (555) 240-9090", "Boston, USA", "Mon–Sat · 8am–8pm", "Established 2009",
         hWork="Our Programs", hSkills="Why BrightMinds"),

    _biz("swift-logistics", "minimal", "studio", "Swift Logistics", "Courier & Logistics",
         _img("1586528116311-ad8dd3c8310d"), "Welcome to", "Get a Quote",
         "Your shipments, delivered fast and tracked every mile — reliable logistics that keep your business moving.",
         "Swift Logistics provides fast, dependable courier and freight services. With smart tracking and a nationwide network, we deliver on our promises — on time, every time.",
         _stat(("2M+", "Deliveries"), ("98%", "On-Time"), ("40", "Cities"), ("12", "Years")),
         _svc(("fa-truck-fast", "Express Delivery", "Same-day and next-day shipping."),
              ("fa-box", "Freight & Cargo", "Reliable bulk and pallet transport."),
              ("fa-warehouse", "Warehousing", "Secure storage and fulfilment."),
              ("fa-location-dot", "Live Tracking", "Know where your parcel is, always.")),
         _skl(("On-Time Delivery", 98), ("Parcel Safety", 99), ("Customer Support", 96), ("Network Coverage", 95)),
         _proj(("Same-Day Network", "Express", _img("1601584115197-04ecc0da31d7"), "Across the city in hours."),
               ("Freight Solutions", "Cargo", _img("1494412574643-ff11b0a5c1c3"), "Heavy loads, handled."),
               ("Smart Warehousing", "Storage", _img("1578575437130-527eed3abbec"), "Organised, secure, efficient."),
               ("Last-Mile Delivery", "Logistics", _img("1566576721346-d4a3b4eaeb55"), "Right to the doorstep.")),
         _tl(("Company Founded", "A few vans", "2012", "Started with local deliveries."),
             ("2 Million Parcels", "Major milestone", "2023", "Delivered across the nation.")),
         _tl(("ISO Certified", "Quality assured", "2019", "Certified logistics operations."),
             ("Safety Accredited", "Top standards", "2021", "Recognised safe transport.")),
         _ach(("fa-trophy", "Best Courier Service", "2023"), ("fa-award", "Reliability Award", "LogiAwards"), ("fa-medal", "Business Choice", "2022")),
         _tst(("Never missed a delivery. Swift keeps our store running smoothly.", "Aman G.", "Business Owner", "https://i.pravatar.cc/100?img=13"),
              ("Fast, trackable and dependable. Exactly what we needed.", "Jennifer L.", "Operations Lead", "https://i.pravatar.cc/100?img=20")),
         "support@swiftlogistics.com", "+1 (555) 980-1212", "Chicago, USA", "Mon–Sat · 24 hours", "Established 2012",
         hWork="Our Solutions", hSkills="Why Swift"),

    # Engineer layout sample
    {
        "slug": "arjun-dev",
        "data": {
            "theme": "noir", "layout": "engineer",
            "name": "Arjun Shah", "role": "Software Engineer",
            "greeting": "Hi, I'm", "tagline": "I build fast, reliable backend systems and clean APIs.",
            "image": _img("1507003211169-0a1dd7228f2d"),
            "ctaText": "View My Work", "resumeText": "Download CV", "resumeUrl": "#",
            "socials": {"github": "#", "linkedin": "#", "twitter": "#"},
            "stats": _stat(("5+", "Years"), ("30+", "Projects"), ("15+", "Clients"), ("99%", "Uptime")),
            "aboutHeading": "About Me",
            "about": "I'm a backend-focused software engineer with 5+ years building scalable systems. I love clean architecture, fast APIs and making complex things simple.",
            "personal": {"email": "arjun@example.com", "phone": "+91 98765 43210",
                         "location": "Bangalore, India", "availability": "Open to remote", "languages": "Python · Go · TypeScript"},
            "services": _svc(
                ("fa-server", "Backend Development", "Scalable APIs and microservices."),
                ("fa-database", "Database Design", "Postgres, Redis, and beyond."),
                ("fa-cloud", "Cloud & DevOps", "AWS, Docker, CI/CD pipelines."),
                ("fa-code", "Code Review", "Clean code, solid architecture."),
            ),
            "skills": _skl(("Python", 95), ("Go", 85), ("TypeScript", 80), ("PostgreSQL", 90), ("Docker", 88), ("AWS", 82)),
            "projects": _proj(
                ("SwiftAPI", "Open Source", _img("1498050108023-c5249f4df085"), "High-performance REST framework in Go."),
                ("DataSync", "SaaS", _img("1551288049-bebda4e38f71"), "Real-time data pipeline for 1M+ events/day."),
                ("AuthKit", "Library", _img("1461749280684-dccba630e2f6"), "JWT auth library used by 2K+ projects."),
                ("Deploy Bot", "Tooling", _img("1517180102446-f3ece451e9d8"), "Slack bot for zero-click deployments."),
            ),
            "experience": _tl(
                ("Senior Engineer", "FinTech Startup", "2021–Now", "Built payment processing at 10K TPS."),
                ("Backend Engineer", "CloudCo", "2019–2021", "Migrated monolith to microservices."),
                ("Junior Dev", "Agency", "2018–2019", "Shipped 8 client projects."),
            ),
            "education": _tl(
                ("B.Tech Computer Science", "IIT Bombay", "2018", "Graduated with distinction."),
            ),
            "achievements": _ach(
                ("fa-trophy", "Open Source Award", "GitHub 2023"),
                ("fa-star", "Top Contributor", "FastAPI Community"),
                ("fa-medal", "Hackathon Winner", "PyCon India 2022"),
            ),
            "testimonials": _tst(
                ("Arjun's API design saved us months of refactoring. Brilliant engineer.", "Priya M.", "CTO, FinStart", "https://i.pravatar.cc/100?img=44"),
                ("Reliable, fast and writes the cleanest code I've reviewed.", "Tom B.", "Lead Engineer", "https://i.pravatar.cc/100?img=15"),
            ),
            "hServices": "What I Do", "hSkills": "Tech Stack", "hWork": "Projects",
            "hResume": "Experience", "hExperience": "Work History", "hEducation": "Education",
            "hAchievements": "Recognition", "hTestimonials": "Kind Words",
            "contactHeading": "Let's Work Together",
            "contactText": "I'm open to freelance projects and full-time remote roles. Drop me a message.",
        }
    },
]


def ensure_samples(db: Session) -> None:
    """Insert all samples if the table is empty. Safe to call on every startup."""
    if db.query(models.SamplePortfolio).count() > 0:
        return
    for s in SAMPLES:
        data = s["data"]
        skills = data.get("skills", [])
        db.add(models.SamplePortfolio(
            slug=s["slug"],
            full_name=data["name"],
            title=data["role"],
            bio=data["about"],
            avatar_url=data["image"],
            skills_json=json.dumps([sk["name"] for sk in skills]),
            data_json=json.dumps(data),
        ))
    db.commit()
    print(f"[startup] Seeded {len(SAMPLES)} sample portfolios.")
